import Head from 'next/head';
import { Navbar } from '../components';
import type { NextPage } from 'next';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
	const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);

	return (
		<>
			<Head>
				<title>Murph</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
				<h1>hello</h1>
			</main>
		</>
	);
};

export default Home;
