import { Hero, Navbar } from '@components';

import Head from 'next/head';
import type { NextPage } from 'next';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
	const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);

	return (
		<>
			<Head>
				<title>Murph</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main className="">
				<Hero />
				<h1>{hello.data ? hello.data.greeting : 'loading...'}</h1>
			</main>
		</>
	);
};

export default Home;
