import { Footer, Navbar } from '@components';

import Head from 'next/head';

type Props = {
	children: React.ReactNode;
	title: string;
};

export const Page: React.FC<Props> = ({ children, title }) => {
	return (
		<>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main>{children}</main>

			<Footer />
		</>
	);
};
